language: ruby
rvm:
  - 2.7.0
install:
  - gem install bundler:1.17.2
  - gem install nokogiri -v '1.9.1' --source 'https://rubygems.org/'
  - bundle install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: develop
