language: ruby
rvm:
- 2.6.4
install:
- bundle install --trace
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: develop
