source 'https://rubygems.org'

gem 'jekyll', '~> 3.8.5'
gem 'jekyll-assets', '~> 3.0.12'
gem 'jekyll-multiple-languages-plugin', '~> 1.6.1'
gem 'jekyll-gzip', '~> 2.4.2'
gem 'maruku', '~> 0.7.3'
gem 'rake', '~> 13.0.1'
gem 'sass', '~> 3.7.4'
gem 'uglifier', '~> 4.2.0'
gem 'github-pages', '~> 204'
gem "sprockets", '~> 3.7'