---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: DEUTSCH
- type: directory
  path: _i18n/de/_posts
  label: Aktuelles
  create: all
  match: "**/*.md"
  new_doc_ext: md
- type: document
  path: _i18n/de/kloster/kloster.md
  label: Kloster
- type: document
  path: _i18n/de/gottesdienste/gottesdienste.md
  label: Gottesdienste
- type: document
  path: _i18n/de/verlag/verlag.md
  label: Verlag
- type: document
  path: _i18n/de/freundeskreis/freundeskreis.md
  label: Freundeskreis
- type: document
  path: _i18n/de/kontakt/kontakt.md
  label: Kontakt
- type: document
  path: _i18n/de/spenden/spenden.md
  label: Spenden
- type: heading
  label: РУССКИЙ
- type: directory
  path: _i18n/ru/_posts
  label: Новости
  create: all
  match: "**/*.md"
  new_doc_ext: md
- type: document
  path: _i18n/ru/kloster/kloster.md
  label: Обитель
- type: document
  path: _i18n/ru/gottesdienste/gottesdienste.md
  label: Службы
- type: document
  path: _i18n/ru/verlag/verlag.md
  label: Издательство
- type: document
  path: pages/galerie.md
  label: Галерея
  read_only: true
- type: document
  path: _i18n/ru/freundeskreis/freundeskreis.md
  label: Попечители
- type: document
  path: _i18n/ru/kontakt/kontakt.md
  label: Контакт
- type: document
  path: _i18n/ru/spenden/spenden.md
  label: Пожертвования
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
