---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url:
sections:
- type: heading
  label: Deutsch
- type: directory
  label: Aktuelles
  path: _i18n/de/_posts
  create: all
  match: "*.md"
  new_doc_ext: md
- type: document
  label: Kloster
  path: _i18n/de/kloster/kloster.md
  read_only: false 
- type: heading
  label: Russisch
- type: directory
  path: _i18n/ru/_posts
  label: Новости
  create: all
  match: "*.md"
  new_doc_ext: md
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
