---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: heading
  label: DEUTSCH
- type: directory
  path: _i18n/de/_posts
  label: Aktuelles
  create: all
  match: "**/*.md"
  new_doc_ext: md
  templates:
  - blogpost
- type: document
  path: _i18n/de/kloster/kloster.md
  label: Kloster
  templates:
  - leeres-template
- type: document
  path: _i18n/de/gottesdienste/gottesdienste.md
  label: Gottesdienste
  templates:
  - leeres-template
- type: document
  path: _i18n/de/verlag/verlag.md
  label: Verlag
  templates:
  - leeres-template
- type: document
  path: _i18n/de/freundeskreis/freundeskreis.md
  label: Freundeskreis
  templates:
  - leeres-template
- type: document
  path: _i18n/de/kontakt/kontakt.md
  label: Kontakt
  templates:
  - leeres-template
- type: document
  path: _i18n/de/spenden/spenden.md
  label: Spenden
  templates:
  - leeres-template
- type: document
  path: pages/impressum.md
  label: Impressum
  templates:
  - leeres-template
- type: heading
  label: РУССКИЙ
- type: directory
  path: _i18n/ru/_posts
  label: Новости
  create: all
  match: "**/*.md"
  new_doc_ext: md
  templates:
  - blogpost
- type: document
  path: _i18n/ru/kloster/kloster.md
  label: Обитель
  templates:
  - leeres-template
- type: document
  path: _i18n/ru/gottesdienste/gottesdienste.md
  label: Службы
  templates:
  - leeres-template
- type: document
  path: _i18n/ru/verlag/verlag.md
  label: Издательство
  templates:
  - leeres-template
- type: document
  path: _i18n/ru/freundeskreis/freundeskreis.md
  label: Попечители
  templates:
  - leeres-template
- type: document
  path: _i18n/ru/kontakt/kontakt.md
  label: Контакт
  templates:
  - leeres-template
- type: document
  path: _i18n/ru/spenden/spenden.md
  label: Пожертвования
  templates:
  - leeres-template
upload_dir: media
public_path: https://res.cloudinary.com/hiobmon/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":year:/:filename:"
instant_preview: 
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
